#!/usr/bin/env python
import tempfile
import shutil
import os
import argparse
import schroot
import logging


env = {
        'PATH': '/usr/sbin:/usr/bin:/sbin:/bin',
        'DEBCONF_DEBUG': 'developer',
}


def call(chroot, cmd, user=None, **kwargs):
    print("")
    print("---> %s" % (cmd,))
    chroot.check_call(cmd, user=user, env=env, **kwargs)


def setup(chroot):
    call(chroot, ["apt-get", "install", "--yes", "eatmydata"], user='root')
    call(chroot, ["eatmydata", "apt-get", "update"], user='root')
    call(chroot, ["eatmydata", "apt-get", "upgrade", "--yes"], user='root')
    # python-support required for pysupport, should be replaced by python2 install method.
    call(chroot, ["eatmydata", "apt-get", "install", "--yes", "git", "build-essential", "debhelper", "cdbs", "python-support"], user='root')
    call(chroot, ["debconf-set-selections", "debconf.conf"], user='root')


def build_git_package(chroot, src, name, branch="master"):
    old_dir = os.getcwd()
    try:
        call(chroot, ["git", "clone", "--branch", branch, src, name])
        os.chdir(name)
        call(chroot, ["dpkg-checkbuilddeps"])
        call(chroot, ["fakeroot", "debian/rules", "binary"])
    finally:
        os.chdir(old_dir)


def add_sources(chroot, tmp_dir, distribution, source):
    if source == "local":
        old_dir = os.getcwd()
        try:
            os.chdir(tmp_dir)
            build_git_package(chroot, "file:///home/brian/tree/django/django-tldap/django-tldap", "django-tldap")
            build_git_package(chroot, "file:///home/brian/tree/django/django-placard/django-placard", "django-placard")
            build_git_package(chroot, "file:///home/brian/tree/django/karaage/karaage", "karaage")
            build_git_package(chroot, "file:///home/brian/tree/django/karaage/karaage-common", "karaage-common")
            build_git_package(chroot, "file:///home/brian/tree/django/karaage/karaage-admin", "karaage-admin")
            build_git_package(chroot, "file:///home/brian/tree/django/karaage/karaage-registration", "karaage-registration")

            with open('Packages', 'w') as f:
                call(chroot, ["dpkg-scanpackages", "."], stdout=f)
        finally:
            os.chdir(old_dir)

        with chroot.create_file('/etc/apt/sources.list', user='root') as f:
            f.write("deb file://%s ./\n" % (tmp_dir))
            f.write("deb http://hq.in.vpac.org:9999/debian %s main\n" % distribution)
            if distribution == "sid":
                distribution = "wheezy"
            f.write("deb http://code.vpac.org/debian/ %s main\n" % distribution)

        with chroot.create_file('/etc/apt/preferences', user='root') as f:
            f.write("Package: *\n")
            f.write("Pin: release l=VPAC\n")
            f.write("Pin-Priority: 500\n")
            f.write("\n")

        allow_unauthenticated = True
    elif source == "github":
        old_dir = os.getcwd()
        try:
            os.chdir(tmp_dir)
            build_git_package(chroot, "git://github.com/VPAC/django-tldap.git", "django-tldap")
            build_git_package(chroot, "git://github.com/VPAC/django-placard.git", "django-placard")
            build_git_package(chroot, "git://github.com/Karaage-Cluster/karaage.git", "karaage")
            build_git_package(chroot, "git://github.com/Karaage-Cluster/karaage-common.git", "karaage-common")
            build_git_package(chroot, "git://github.com/Karaage-Cluster/karaage-admin.git", "karaage-admin")
            build_git_package(chroot, "git://github.com/Karaage-Cluster/karaage-registration.git", "karaage-registration")

            with open('Packages', 'w') as f:
                call(chroot, ["dpkg-scanpackages", "."], stdout=f)
        finally:
            os.chdir(old_dir)

        with chroot.create_file('/etc/apt/sources.list', user='root') as f:
            f.write("deb file://%s ./\n" % (tmp_dir))
            f.write("deb http://hq.in.vpac.org:9999/debian %s main\n" % distribution)
            if distribution == "sid":
                distribution = "wheezy"
            f.write("deb http://code.vpac.org/debian/ %s main\n" % distribution)

        with chroot.create_file('/etc/apt/preferences', user='root') as f:
            f.write("Package: *\n")
            f.write("Pin: release l=VPAC\n")
            f.write("Pin-Priority: 500\n")
            f.write("\n")

        allow_unauthenticated = True
    elif source == "vpac":

        with chroot.create_file('/etc/apt/sources.list', user='root') as f:
            f.write("deb http://hq.in.vpac.org:9999/debian %s main\n" % distribution)
            if distribution == "sid":
                distribution = "wheezy"
            f.write("deb http://code.vpac.org/debian/ %s main\n" % distribution)

        with chroot.create_file('/etc/apt/preferences', user='root') as f:
            pass

        allow_unauthenticated = False
    else:

        raise RuntimeError("Oops. Unknown source.")

    call(chroot, ["apt-key", "add", "vpac/vpac-debian-key.gpg"], user='root')
    call(chroot, ["eatmydata", "apt-get", "update"], user='root')

    return allow_unauthenticated


def install_mysql(chroot, sql_file):
    call(chroot, ["eatmydata", "apt-get", "install", "--yes", "mysql-server"], user='root')

    with open('mysql/setup.sql', 'r') as f:
        call(chroot, ["mysql", "--user=root", "--password=mysqlsecret"], stdin=f)

    if sql_file is not None:
        with open(sql_file, 'r') as f:
            call(chroot, ["mysql", "--user=root", "--password=mysqlsecret"], stdin=f)

def install_openldap(chroot, ldif_file):
    call(chroot, ["eatmydata", "apt-get", "install", "--yes", "slapd", "ldap-utils"], user='root')

    # load ppolicy schema
    with open('openldap/ppolicy.ldif', 'r') as f:
        call(chroot, ["ldapadd", "-Y", "EXTERNAL", "-H", "ldapi:///"], stdin=f, user='root')

    # load ppolicy module
    with open('openldap/ppolicy1.ldif', 'r') as f:
        call(chroot, ["ldapadd", "-Y", "EXTERNAL", "-H", "ldapi:///"], stdin=f, user='root')

    if ldif_file is None:

        # load default ppolicy policy
        with open('openldap/ppolicy2.ldif', 'r') as f:
            call(chroot, ["ldapadd", "-x", "-H", "ldapi:///", "-D", "cn=admin,dc=example,dc=org", "-w", "slapdsecret"], stdin=f)

        # configure default ppolicy policy
        with open('openldap/ppolicy3.ldif', 'r') as f:
            call(chroot, ["ldapadd", "-Y", "EXTERNAL", "-H", "ldapi:///"], stdin=f, user='root')

    else:

        # reconfigure base DN
        with open(ldif_file + '-config.ldif', 'r') as f:
            call(chroot, ["ldapmodify", "-Y", "EXTERNAL", "-H", "ldapi:///"], stdin=f, user='root')

        # kill existing data
        call(chroot, ["service", "slapd", "stop"], user='root')
        call(chroot, ["rm", "-rf", "/var/lib/ldap/"], user='root')
        call(chroot, ["mkdir", "/var/lib/ldap/"], user='root')
        with open('/dev/null', 'r') as f:
            call(chroot, ["slapadd"], stdin=f, user='root')
        call(chroot, ["slapindex"], user='root')
        call(chroot, ["chown", "openldap:openldap", "-R", "/var/lib/ldap/"], user='root')
        call(chroot, ["service", "slapd", "start"], user='root')

        # load default ppolicy policy
        call(chroot, ["service", "slapd", "stop"], user='root')
        with open(ldif_file + '-ppolicy2.ldif', 'r') as f:
            call(chroot, ["slapadd"], stdin=f, user='root')
        call(chroot, ["slapindex"], user='root')
        call(chroot, ["chown", "openldap:openldap", "-R", "/var/lib/ldap/"], user='root')
        call(chroot, ["service", "slapd", "start"], user='root')

        # configure default ppolicy policy
        with open(ldif_file + '-ppolicy3.ldif', 'r') as f:
            call(chroot, ["ldapadd", "-Y", "EXTERNAL", "-H", "ldapi:///"], stdin=f, user='root')

        # load VPAC data
        call(chroot, ["service", "slapd", "stop"], user='root')
        with open(ldif_file + '.ldif', 'r') as f:
            call(chroot, ["slapadd"], stdin=f, user='root')
        call(chroot, ["slapindex"], user='root')
        call(chroot, ["chown", "openldap:openldap", "-R", "/var/lib/ldap/"], user='root')
        call(chroot, ["service", "slapd", "start"], user='root')

def install_389(chroot, ldif_file):
    call(chroot, ["eatmydata", "apt-get", "install", "--yes", "389-ds-base", "ldap-utils"], user='root')
    call(chroot, ["setup-ds", "-s", "-f", "389/setup.inf"], user='root')
#    with open('389/app.ldif', 'r') as f:
#        call(chroot, ["ldapmodify", "-D", "cn=Directory Manager", "-w", "slapsecret"], stdin=f, user='root')

def install_karaage(chroot, allow_unauthenticated):
    args = []
    if allow_unauthenticated:
        args += ["--allow-unauthenticated"]

    call(chroot, ["eatmydata", "apt-get", "install", "--yes", "libjs-jquery-ui", "python-mysqldb"], user='root')
    call(chroot, ["eatmydata", "apt-get", "install", "--yes", "apache2.2", "libapache2-mod-wsgi" ], user='root')
    call(chroot, ["eatmydata", "apt-get", "install", "--yes", "karaage"] + args, user='root')
    call(chroot, ["eatmydata", "apt-get", "install", "--yes", "karaage-admin", "karaage-registration"] + args, user='root')

def config_karaage(chroot, karaage_file):
    chroot.copy(karaage_file, "/etc/karaage/global_settings.py", user="root")
    call(chroot, ["kg_set_secret_key"], user='root')
    call(chroot, ["chmod", "a+r", "/etc/karaage/global_settings.py"], user='root')
    call(chroot, ["ln", "-s", "/etc/karaage/kgadmin-apache.conf", "/etc/apache2/conf.d/"], user='root')
    call(chroot, ["ln", "-s", "/etc/karaage/kgreg-apache.conf", "/etc/apache2/conf.d/"], user='root')
    call(chroot, ["service", "apache2", "restart"], user='root')

    call(chroot, ["kg-manage", "syncdb", "--noinput"], user='root')
    call(chroot, ["kg-manage", "migrate", "--all", "--traceback"], user='root')
    call(chroot, ["kg-manage", "kgcreatesuperuser",
        "--username=kgadmin", "--email=kgadmin@example.org", "--password=1234",
        "--first_name=karaage", "--last_name=admin", "--institute=test"],
        user='root')

def remove_karaage(chroot):
    call(chroot, ["eatmydata", "apt-get", "remove", "--purge", "--yes", "karaage-admin", "karaage-registration"], user='root')
    call(chroot, ["eatmydata", "apt-get", "autoremove", "--purge", "--yes" ], user='root')


def test_karaage(chroot, tmp_dir, args):
    setup(chroot)
    allow_unauthenticated = add_sources(chroot, tmp_dir, args.distribution, args.source)
    install_mysql(chroot, args.sql)
    if args.ldap == 'openldap':
        install_openldap(chroot, args.ldif)
        karaage_file = args.karaage or "openldap/global_settings.py"
    elif args.ldap == '389':
        install_389(chroot, args.ldif)
        karaage_file = args.karaage or "389/global_settings.py"
    else:
        raise RuntimeError("Unknown ldap server '%s'" % args.ldap)
    install_karaage(chroot, allow_unauthenticated)
    config_karaage(chroot, karaage_file)
    if args.shell:
        print("")
        print("Configured. tmp_dir=%s" % tmp_dir)
        print("Entering shell, please exit to finish.")
        call(chroot, ["bash"], user='root')
    remove_karaage(chroot)


def main():
    parser = argparse.ArgumentParser(description='Test karaage Debian packages.')
    parser.add_argument("-d", "--distribution", choices=['squeeze', 'wheezy', 'sid'], default="wheezy", help="Which distribution?")
    parser.add_argument("-l", "--ldap", choices=['openldap', '389'], default="openldap", help="Which LDAP server?")
    parser.add_argument("-s", "--source", choices=['local', 'github', 'vpac'], default="github", help="Where to get packages from")
    parser.add_argument("-r", "--shell", action="store_true", help="Run shell on configured")
    parser.add_argument("-e", "--error", action="store_true", help="Run shell on error")
    parser.add_argument("-S", "--sql", help="Initialise mysql with this sql file")
    parser.add_argument("-L", "--ldif", help="Initialise openldap with this file")
    parser.add_argument("-k", "--karaage", help="Karaage config file to use")
    args = parser.parse_args()

    logging.basicConfig(level=logging.DEBUG)

    tmp_dir = None
    try:
        tmp_dir = tempfile.mkdtemp()

        with schroot.schroot(args.distribution) as chroot:
            try:
                test_karaage(chroot, tmp_dir, args)
            except Exception, e:
                if args.error:
                    print("")
                    print("Exception occured. tmp_dir=%s" % tmp_dir)
                    print(e)
                    print("Entering shell, please exit to finish.")
                    call(chroot, ["bash"], user='root')
                raise

    finally:
        try:
            if tmp_dir is not None:
                shutil.rmtree(tmp_dir) # delete directory
        except OSError, e:
            if e.errno != 2: # code 2 - no such file or directory
                raise

if __name__ == "__main__":
    main()
