#!/usr/bin/python
import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'kgadmin.conf.settings'
from django.db import connection
tables = connection.introspection.table_names()
seen_models = connection.introspection.installed_models(tables)

for table in tables:
	models = connection.introspection.installed_models([table])
	if len(models) == 0:
		print table

#print seen_models
